# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session_info_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 70)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(350, 15))
        Form.setMaximumSize(QtCore.QSize(500, 70))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.session_info_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.session_info_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.session_info_layout.setContentsMargins(0, 0, 0, 0)
        self.session_info_layout.setSpacing(0)
        self.session_info_layout.setObjectName("session_info_layout")
        spacerItem = QtWidgets.QSpacerItem(
            5, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem)
        self.session_time_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.session_time_label.sizePolicy().hasHeightForWidth()
        )
        self.session_time_label.setSizePolicy(sizePolicy)
        self.session_time_label.setMinimumSize(QtCore.QSize(110, 15))
        self.session_time_label.setMaximumSize(QtCore.QSize(110, 15))
        self.session_time_label.setObjectName("session_time_label")
        self.session_info_layout.addWidget(self.session_time_label)
        spacerItem1 = QtWidgets.QSpacerItem(
            30, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem1)
        self.azimuth_session_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.azimuth_session_label.sizePolicy().hasHeightForWidth()
        )
        self.azimuth_session_label.setSizePolicy(sizePolicy)
        self.azimuth_session_label.setMinimumSize(QtCore.QSize(30, 15))
        self.azimuth_session_label.setMaximumSize(QtCore.QSize(30, 15))
        self.azimuth_session_label.setAlignment(QtCore.Qt.AlignCenter)
        self.azimuth_session_label.setObjectName("azimuth_session_label")
        self.session_info_layout.addWidget(self.azimuth_session_label)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem2)
        self.elevation_session_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.elevation_session_label.sizePolicy().hasHeightForWidth()
        )
        self.elevation_session_label.setSizePolicy(sizePolicy)
        self.elevation_session_label.setMinimumSize(QtCore.QSize(30, 15))
        self.elevation_session_label.setMaximumSize(QtCore.QSize(30, 15))
        self.elevation_session_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elevation_session_label.setObjectName("elevation_session_label")
        self.session_info_layout.addWidget(self.elevation_session_label)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem3)
        self.sun_azimuth_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.sun_azimuth_label.sizePolicy().hasHeightForWidth()
        )
        self.sun_azimuth_label.setSizePolicy(sizePolicy)
        self.sun_azimuth_label.setMinimumSize(QtCore.QSize(30, 15))
        self.sun_azimuth_label.setMaximumSize(QtCore.QSize(30, 15))
        self.sun_azimuth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sun_azimuth_label.setObjectName("sun_azimuth_label")
        self.session_info_layout.addWidget(self.sun_azimuth_label)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem4)
        self.sun_elevation_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.sun_elevation_label.sizePolicy().hasHeightForWidth()
        )
        self.sun_elevation_label.setSizePolicy(sizePolicy)
        self.sun_elevation_label.setMinimumSize(QtCore.QSize(30, 15))
        self.sun_elevation_label.setMaximumSize(QtCore.QSize(30, 15))
        self.sun_elevation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sun_elevation_label.setObjectName("sun_elevation_label")
        self.session_info_layout.addWidget(self.sun_elevation_label)
        spacerItem5 = QtWidgets.QSpacerItem(
            25, 15, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.session_info_layout.addItem(spacerItem5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.session_time_label.setText(_translate("Form", "Time UTC"))
        self.azimuth_session_label.setText(_translate("Form", "Az"))
        self.elevation_session_label.setText(_translate("Form", "El"))
        self.sun_azimuth_label.setText(_translate("Form", "SunAz"))
        self.sun_elevation_label.setText(_translate("Form", "SunEl"))
