version: 1
disable_existing_loggers: False


formatters:
  default_formatter:
    format: "[{asctime}] #{levelname:8} {filename}:{lineno} - {name} - {message}"
    datefmt: "%Y-%m-%d %H:%M:%S"
    style: "{"


filters:
  info_filter:
    (): orbisat.info_logger.logging_services.custom_filters.InfoLogFilter


handlers:
  info_console_handler:
    class: logging.StreamHandler
    formatter: default_formatter
    level: INFO
    stream: "ext://sys.stdout"

  error_console_handler:
    class: logging.StreamHandler
    formatter: default_formatter
    level: WARNING
    stream: "ext://sys.stderr"

  info_file_handler:
    class: orbisat.info_logger.logging_services.custom_handlers.LogRotatiingFileHandler
    formatter: default_formatter
    level: INFO
    filename: Logs/orbisat_info.log
    when: midnight
    utc: False
    backupCount: 365
    filters: [info_filter]

  error_file_handler:
    class: logging.FileHandler
    formatter: default_formatter
    level: WARNING
    filename: Logs/orbisat_errors.log
    mode: a

  orbisat_gui_info_file_handler:
    class: orbisat.info_logger.logging_services.custom_handlers.LogRotatiingFileHandler
    formatter: default_formatter
    level: DEBUG
    filename: Logs/orbisat_gui_info.log
    when: midnight
    utc: False
    backupCount: 365
    filters: [info_filter]

  orbisat_gui_error_file_handler:
    class: logging.FileHandler
    formatter: default_formatter
    level: WARNING
    filename: Logs/orbisat_gui_errors.log
    mode: a



loggers:
  orbisat.orbisat_main.orbisat:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.tcp.TcpServerABC:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.tcp.orbisat_tcp_server:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.tcp.orbisat_tcp_client:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.orbisat_services.satellite:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.orbisat_services.ground_station:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.orbisat_services.communication:
    level: INFO
    handlers: [info_file_handler, error_file_handler]

  orbisat.orbisat_gui.gui_main_full:
    level: DEBUG
    handlers: [orbisat_gui_info_file_handler, orbisat_gui_error_file_handler]

  orbisat.orbisat_gui.gui_main_short:
    level: DEBUG
    handlers: [orbisat_gui_info_file_handler, orbisat_gui_error_file_handler]

  orbisat.orbisat_gui.gui_station_setup:
    level: DEBUG
    handlers: [orbisat_gui_info_file_handler, orbisat_gui_error_file_handler]

  orbisat.orbisat_gui.gui_choose_station:
    level: DEBUG
    handlers: [orbisat_gui_info_file_handler, orbisat_gui_error_file_handler]